"""
mcp_gui_tester against generic (non-MoleditPy) server behaviours:
SSE-framed responses, paginated tools/list, the handshake-era
``notifications/initialized`` + ``MCP-Protocol-Version`` requirements,
https URLs, and union / non-string enum schemas as generated by common
server SDKs.

A tiny scripted ``http.server`` stands in for the server so each behaviour
can be switched on independently. Real PyQt6 offscreen; skipped when PyQt6
is unavailable.
"""

from __future__ import annotations

import json
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import pytest
from test_mcp_tester import _has_pyqt6, _load_tester

pytestmark = pytest.mark.skipif(not _has_pyqt6(), reason="PyQt6 not installed")


@pytest.fixture(scope="module")
def app():
    from PyQt6.QtWidgets import QApplication

    return QApplication.instance() or QApplication([])


@pytest.fixture(scope="module")
def mod(app):
    return _load_tester()


# ---------------------------------------------------------------------------
# Scripted legacy-era server
# ---------------------------------------------------------------------------

TOOLS = [{"name": f"tool_{i}", "inputSchema": {"type": "object"}} for i in range(5)]


class _Script:
    def __init__(
        self,
        sse=False,
        page_size=None,
        require_initialized=False,
        loop_cursor=False,
        negotiated="2025-06-18",
    ):
        self.sse = sse
        self.page_size = page_size
        self.require_initialized = require_initialized
        self.loop_cursor = loop_cursor
        self.negotiated = negotiated
        self.initialized = False
        self.requests: list = []


def _serve(script: _Script):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *args):  # silence
            pass

        def do_POST(self):
            body = json.loads(self.rfile.read(int(self.headers["Content-Length"])))
            script.requests.append((body, self.headers))  # case-insensitive lookup
            method = body.get("method")
            if "id" not in body:  # notification
                if method == "notifications/initialized":
                    script.initialized = True
                self.send_response(202)
                self.end_headers()
                return
            if method == "initialize":
                result = {
                    "protocolVersion": script.negotiated,
                    "serverInfo": {"name": "scripted", "version": "1"},
                    "capabilities": {"tools": {}},
                }
            elif script.require_initialized and not script.initialized:
                self._reply(
                    {
                        "jsonrpc": "2.0",
                        "id": body["id"],
                        "error": {"code": -32600, "message": "not initialized"},
                    }
                )
                return
            elif method == "tools/list":
                if script.page_size is None:
                    result = {"tools": TOOLS}
                else:
                    start = int((body.get("params") or {}).get("cursor") or 0)
                    page = TOOLS[start : start + script.page_size]
                    result = {"tools": page}
                    nxt = start + script.page_size
                    if script.loop_cursor:
                        result["nextCursor"] = "0"
                    elif nxt < len(TOOLS):
                        result["nextCursor"] = str(nxt)
            elif method == "tools/call":
                result = {"content": [{"type": "text", "text": "called"}]}
            else:
                self._reply(
                    {
                        "jsonrpc": "2.0",
                        "id": body["id"],
                        "error": {"code": -32601, "message": "nope"},
                    }
                )
                return
            self._reply({"jsonrpc": "2.0", "id": body["id"], "result": result})

        def _reply(self, message):
            if script.sse:
                # A server notification first, then the response, split over
                # two data: lines, with a comment and a retry field mixed in.
                note = {
                    "jsonrpc": "2.0",
                    "method": "notifications/message",
                    "params": {"level": "info", "data": "hi"},
                }
                text = json.dumps(message, indent=1)
                data = "\n".join("data: " + line for line in text.splitlines())
                raw = (
                    ": keep-alive\n\nretry: 100\n\n"
                    f"event: message\ndata: {json.dumps(note)}\n\n"
                    f"event: message\n{data}\n\n"
                ).encode()
                ctype = "text/event-stream"
            else:
                raw = json.dumps(message).encode()
                ctype = "application/json"
            self.send_response(200)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(raw)))
            self.send_header("Mcp-Session-Id", "sess-1")
            self.end_headers()
            self.wfile.write(raw)

    server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server, f"http://127.0.0.1:{server.server_address[1]}/mcp"


@pytest.fixture
def scripted():
    servers = []

    def _make(**kw):
        script = _Script(**kw)
        server, url = _serve(script)
        servers.append(server)
        return script, url

    yield _make
    for s in servers:
        s.shutdown()
        s.server_close()


def test_sse_framed_responses_are_decoded(mod, scripted):
    _script, url = scripted(sse=True)
    client = mod.MCPClient(url, protocol="legacy")
    info = client.connect()
    assert info["serverInfo"]["name"] == "scripted"
    assert [t["name"] for t in client.list_tools()] == [t["name"] for t in TOOLS]
    assert client.call_tool("tool_0", {})["content"][0]["text"] == "called"


def test_initialized_notification_is_sent(mod, scripted):
    script, url = scripted(require_initialized=True)
    client = mod.MCPClient(url, protocol="legacy")
    client.connect()
    assert script.initialized
    assert len(client.list_tools()) == len(TOOLS)
    note = [
        b for b, _ in script.requests if b.get("method") == "notifications/initialized"
    ]
    assert note and "id" not in note[0]


def test_negotiated_version_header_after_handshake(mod, scripted):
    script, url = scripted(negotiated="2025-06-18")
    client = mod.MCPClient(url, protocol="legacy")
    client.connect()
    client.list_tools()
    by_method = {b.get("method"): h for b, h in script.requests}
    assert "MCP-Protocol-Version" not in by_method["initialize"]
    assert by_method["tools/list"]["MCP-Protocol-Version"] == "2025-06-18"
    assert by_method["tools/list"]["Mcp-Session-Id"] == "sess-1"


def test_paginated_tools_list_is_followed(mod, scripted):
    script, url = scripted(page_size=2)
    client = mod.MCPClient(url, protocol="legacy")
    client.connect()
    assert [t["name"] for t in client.list_tools()] == [t["name"] for t in TOOLS]
    cursors = [
        (b.get("params") or {}).get("cursor")
        for b, _ in script.requests
        if b.get("method") == "tools/list"
    ]
    assert cursors == [None, "2", "4"]


def test_cursor_loop_terminates(mod, scripted):
    _script, url = scripted(page_size=2, loop_cursor=True)
    client = mod.MCPClient(url, protocol="legacy")
    client.connect()
    assert len(client.list_tools()) == 4  # first page + one follow before the repeat


def test_non_string_header_values_are_sent_as_text(mod, scripted):
    script, url = scripted()
    client = mod.MCPClient(
        url, headers={"X-Retries": 3, "X-Flag": True}, protocol="legacy"
    )
    client.connect()
    _, headers = script.requests[0]
    assert headers["X-Retries"] == "3" and headers["X-Flag"] == "True"


# ---------------------------------------------------------------------------
# Pure helpers
# ---------------------------------------------------------------------------


def test_parse_sse_messages_skips_non_data_and_bad_json(mod):
    body = ': c\n\nretry: 5\n\ndata: {"a": 1}\n\ndata: not json\n\ndata:{"b":2}'
    assert mod.parse_sse_messages(body) == [{"a": 1}, {"b": 2}]


def test_pick_response_by_id_and_fallback(mod):
    msgs = [{"method": "x"}, {"id": 1, "result": 1}, {"id": 2, "result": 2}]
    assert mod.pick_response(msgs, 1)["result"] == 1
    assert mod.pick_response(msgs, 99)["result"] == 2
    assert mod.pick_response([{"method": "x"}], 1) == {}


def test_split_url_with_scheme(mod):
    assert mod.split_url_with_scheme("https://example.org/mcp") == (
        "example.org",
        443,
        "/mcp",
        "https",
    )
    assert mod.split_url_with_scheme("https://example.org:8443/x") == (
        "example.org",
        8443,
        "/x",
        "https",
    )
    assert mod.split_url_with_scheme("host:9000") == ("host", 9000, "/mcp", "http")
    assert mod.split_url_with_scheme("ftp://h/p")[3] == "http"


def test_build_url(mod):
    assert (
        mod.build_url("https", "example.org", 443, "mcp")
        == "https://example.org:443/mcp"
    )
    assert mod.build_url("http", "::1", 7891, "/mcp") == "http://[::1]:7891/mcp"


def test_non_json_body_reports_content(mod):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *a):
            pass

        def do_POST(self):
            self.rfile.read(int(self.headers["Content-Length"]))
            raw = b"<html>proxy login</html>"
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.send_header("Content-Length", str(len(raw)))
            self.end_headers()
            self.wfile.write(raw)

    server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    try:
        client = mod.MCPClient(
            f"http://127.0.0.1:{server.server_address[1]}/mcp", protocol="legacy"
        )
        with pytest.raises(RuntimeError, match="not JSON.*text/html.*proxy login"):
            client.connect()
    finally:
        server.shutdown()
        server.server_close()


def test_error_member_that_is_not_an_object(mod):
    with pytest.raises(mod.MCPError, match="boom"):
        mod.MCPClient._raise_for_error({"error": "boom"}, 500)


# ---------------------------------------------------------------------------
# Schema forms generated by other SDKs
# ---------------------------------------------------------------------------


def _field(mod, name, schema, required=False):
    return mod.ParamField(name, schema, required)


def test_optional_int_via_anyof_gets_spinbox_and_sends_int(mod):
    from PyQt6.QtWidgets import QSpinBox

    f = _field(
        mod, "n", {"anyOf": [{"type": "integer"}, {"type": "null"}], "default": 4}
    )
    assert isinstance(f.widget, QSpinBox)
    assert f.value() == 4


def test_type_list_union_gets_member_widget(mod):
    from PyQt6.QtWidgets import QDoubleSpinBox

    f = _field(mod, "x", {"type": ["number", "null"]})
    assert isinstance(f.widget, QDoubleSpinBox)


def test_anyof_string_or_array_coerces_json(mod):
    f = _field(mod, "lines", {"anyOf": [{"type": "string"}, {"type": "array"}]})
    f.widget.setPlainText('["a", "b"]')
    assert f.value() == ["a", "b"]
    f.widget.setPlainText("plain")
    assert f.value() == "plain"


def test_anyof_int_or_string_line_edit_coerces_numbers(mod):
    f = _field(mod, "id", {"anyOf": [{"type": "integer"}, {"type": "string"}]})
    f.widget.setText("42")
    assert f.value() == 42


def test_integer_enum_keeps_json_type(mod):
    f = _field(mod, "level", {"type": "integer", "enum": [1, 2, 3], "default": 2})
    assert f.value() == 2 and isinstance(f.value(), int)
    f.set_value(3)
    assert f.value() == 3
    f.set_value("1")  # remembered as text still selects the matching member
    assert f.value() == 1
    f.set_value(99)  # unknown value leaves the selection alone
    assert f.value() == 1


def test_boolean_enum_default_not_confused_with_int(mod):
    f = _field(mod, "mode", {"enum": [1, True], "default": True})
    assert f.value() is True


def test_object_default_is_prefilled(mod):
    f = _field(mod, "opts", {"type": "object", "default": {"a": 1}})
    assert f.value() == {"a": 1}


# ---------------------------------------------------------------------------
# Window: scheme selection and refresh state
# ---------------------------------------------------------------------------


def test_window_takes_https_scheme_from_url(mod):
    win = mod.MCPTesterWindow("https://example.org/mcp")
    assert win.scheme_combo.currentText() == "https"
    assert win.port_spin.value() == 443


def test_full_url_pasted_into_host_is_split(mod, monkeypatch):
    win = mod.MCPTesterWindow("http://127.0.0.1:7891/mcp")
    captured = {}
    monkeypatch.setattr(
        win, "_run", lambda fn, client, on_done: captured.setdefault("url", client.url)
    )
    win.host_edit.setText("https://example.org:8443/api/mcp")
    win._on_connect()
    assert captured["url"] == "https://example.org:8443/api/mcp"
    assert win.host_edit.text() == "example.org"
    assert win.scheme_combo.currentText() == "https"
    assert not win.refresh_btn.isEnabled()


def test_refresh_stays_disabled_after_failed_connect(mod, monkeypatch):
    win = mod.MCPTesterWindow("http://127.0.0.1:7891/mcp")
    monkeypatch.setattr(mod.QMessageBox, "critical", lambda *a, **k: None)
    monkeypatch.setattr(win, "_run", lambda fn, client, on_done: None)
    win._on_connect()
    win._on_error("Connection failed: refused")
    assert not win.refresh_btn.isEnabled()


def test_call_done_tolerates_missing_and_structured_content(mod):
    win = mod.MCPTesterWindow("http://127.0.0.1:7891/mcp")
    win._on_call_done({})
    assert win.result_text.toPlainText() == ""
    win._on_call_done({"content": ["junk"], "structuredContent": {"k": 1}})
    assert '"k": 1' in win.result_text.toPlainText()


# ---------------------------------------------------------------------------
# Remaining branches
# ---------------------------------------------------------------------------


def test_error_on_initialized_notification_is_tolerated(mod, monkeypatch):
    client = mod.MCPClient("http://127.0.0.1:1/mcp", protocol="legacy")

    def fake_post(payload, extra=None):
        if payload["method"] == "initialize":
            return {
                "result": {"protocolVersion": "2025-06-18", "serverInfo": {"name": "s"}}
            }
        raise mod.MCPError(-32601, "no notifications here")

    monkeypatch.setattr(client, "_post", fake_post)
    assert client.connect()["protocolVersion"] == "2025-06-18"


def test_non_object_json_response_is_rejected(mod):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *a):
            pass

        def do_POST(self):
            self.rfile.read(int(self.headers["Content-Length"]))
            raw = b"[1, 2]"
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(raw)))
            self.end_headers()
            self.wfile.write(raw)

    server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    try:
        client = mod.MCPClient(
            f"http://127.0.0.1:{server.server_address[1]}/mcp", protocol="legacy"
        )
        with pytest.raises(TypeError, match="Unexpected JSON-RPC response"):
            client.connect()
    finally:
        server.shutdown()
        server.server_close()


@pytest.mark.parametrize(
    "alts, default, widget, expected",
    [
        (["boolean", "integer"], True, "QCheckBox", True),
        (["integer", "boolean"], 5, "QSpinBox", 5),
        (["number", "boolean"], 2.5, "QDoubleSpinBox", 2.5),
        (["x-foo", "x-bar"], "raw", "QLineEdit", "raw"),
        (["null", "integer", "boolean"], 7, "QSpinBox", 7),
    ],
)
def test_multi_type_scalar_unions_use_first_member_widget(
    mod, alts, default, widget, expected
):
    import PyQt6.QtWidgets as W

    f = _field(mod, "v", {"anyOf": [{"type": t} for t in alts], "default": default})
    assert isinstance(f.widget, getattr(W, widget))
    assert f.value() == expected


def test_string_scalar_union_widgets(mod):
    from PyQt6.QtWidgets import QLineEdit, QPlainTextEdit

    multi = _field(
        mod,
        "code",
        {"anyOf": [{"type": "string"}, {"type": "integer"}], "default": "x = 1"},
    )
    assert isinstance(multi.widget, QPlainTextEdit) and multi.value() == "x = 1"
    line = _field(
        mod,
        "id",
        {"anyOf": [{"type": "string"}, {"type": "integer"}], "default": "abc"},
    )
    assert isinstance(line.widget, QLineEdit) and line.value() == "abc"
